<?php insert_header(); ?>

<h2>About</h2>

<h3>Objective</h3>
<p>To encourage improvement in interested members.  If you are insterested, you should be serious about improving and be available to play serious games on a regular basis.</p>

<h3>Overview</h3>
<p>There will be separate groups each consisting of players of about the same strength level in order to provide suitable even games.</p>
<p>Based on the relative clustering of strengths, the most effective league strength breakdown at the moment seems to be the following:</p>
<ul>
    <li>~1 dan</li>
    <li>~6 kyu</li>
</ul>
<p>Every round, members of each group will play each other in a round-robbin format.  Games should be scheduled informally by the players individually based on their convenience.  Each round will last one or more weeks, depending on the size of each group.  Groups do not have to have their rounds synchronized.  The round interval is subject to change.</p>

<h3>Reviews</h3>
<p>Each game in the league will be given a short review by either Gus or Greg to cover the important points.</p>

<h3>The Prize</h3>
<p>The winner of each round will get to play a handicap game followed by review with both Gus and Greg.  This winner should choose an appropriate handicap.  You will not learn as much if a game is too easy or too difficult.</p>

<?php insert_footer(); ?>