</div>

<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="27%">&nbsp;</td>
    <td width="50%"><font size="-2">
    Copyright &copy; 1997-2008 American Go Association<br>
    Email the AGA at <a href="mailto:aga@usgo.org">aga@usgo.org</a><br>

    Email our webmaster at <a href="mailto:webmaster@usgo.org">webmaster@usgo.org</a>
    <br /><a href="http://www.usgo.org/mylinks.htm">Hosted at CT Incorporated</a></font>
    </td><td width="23%">&nbsp;</td>
  </tr> 
</table>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-5081638-2");
pageTracker._initData();
pageTracker._trackPageview();
</script>

</body>
</html>
