</div>

<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="27%">&nbsp;</td>
    <td width="50%"><font size="-2">
    Copyright &copy; 1997-2008 American Go Association<br>
    Email the AGA at <a href="mailto:aga@usgo.org">aga@usgo.org</a><br>

    Email our webmaster at <a href="mailto:webmaster@usgo.org">webmaster@usgo.org</a>
    <br /><a href="http://www.usgo.org/mylinks.htm">Hosted at CT Incorporated</a></font>
    </td><td width="23%">&nbsp;</td>
  </tr> 
</table>

</body>
</html>
