<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<title>North American Ing Masters 2008</title>
<link rel="stylesheet" href="/naim/style.css" type="text/css">
<script type="text/javascript" src="/naim/jquery.js"></script>
<script>
eidogoConfig = {enableShortcuts: true};
</script>
<script type="text/javascript" src="http://eidogo.com/player/js/all.compressed.js"></script>
</head>
<body>

<?php include(dirname(__FILE__) . "/../includes/topnav.html"); ?>

<div id="sidebar">
<?php include(dirname(__FILE__) . "/../includes/leftnav.inc"); ?>
</div>

<div id="content">
