<?php include("../../new/header.phtml"); ?>

<h2>Empty Sky League</h2>

<p>An ongoing tournament based on friendly competition to promote learning.</p>
<ul>
    <li><a href="about">About</a></li>
    <li><a href="rules">Rules</a></li>
    <li><a href="standings">Player Standings</a></li>
    <li><a href="archive">Archived Weekly Results</a></li>
    <li><a href="mailto:league@emptysky.org">Sign me up!</a></li>
</ul>

<?php include("../../new/footer.phtml"); ?>