<?php insert_header(); ?>

<h2>Empty Sky League</h2>

<p>An ongoing tournament based on friendly competition to promote learning.</p>
<ul>
    <li><a href="<?=href("about")?>">About</a></li>
    <li><a href="<?=href("rules")?>">Rules</a></li>
    <li><a href="<?=href("rounds/current")?>">Current Round Results</a></li>
    <li><a href="<?=href("rounds")?>">Archived Weekly Results</a></li>
    <li><a href="mailto:league@emptysky.org">Sign me up!</a></li>
</ul>

<?php insert_footer(); ?>