<?php include(HEADER_PATH); ?>

<h2>League Rules</h2>

<h3>Game Rules</h3>
<ul>
<li>All even games</li>
<li><b>No</b> time limit (to encourage thinking; do NOT abuse this)</li>
<li>AGA Rules (7.5 komi)</li>
</ul>

<h3>Absence</h3>
<p>If you no longer have time to participate, that's fine.  Please just let 
Greg know ASAP so that this can be taken into account.  Hunting 
people 
down to get them to finish their games is incredibly annoying, and Greg 
will be really pissed off if you make him do this.  You can rejoin later 
when you have more time.</p>

<?php include(FOOTER_PATH); ?>